### ISSUE TITLE
generic item bug

### ISSUE THREAD

**Issue by BlueAgentReturns** [Turtlemaster200/Shrek-Furniture#5]
yo we cant see shit dude, we gotta fix this shit ASAP

**Comment by Turtlemaster200** [comment]
o no im on it

**Comment by Turtlemaster200** [comment]
i think i may know the problem
in my earlier mod, it worked without the metadata file.
Im gonna try and do it, but removing the metadata until our mod is done.

(Also, this step is useless to us, i found out, because when you upload a mod to the workshop, it automagically creates a bug-free metadata.)

**Comment by Turtlemaster200** [comment]
Nevermind, we dont need the metadata yet, but i found the real problem! We put the objects folder, in the items folder!

Woops on my part. Had to delete everything and put it back in.
